// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yorijihyeahhfprgjkvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvcmlqaWh5ZWFoaGZwcmdqa3ZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4ODE1OTYsImV4cCI6MjA1NTQ1NzU5Nn0.FoRY2ru-hRSa88rIKSE5V5cmX7oc4ESKDUCqEF0gsVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);